# Use the Python 3 alpine official image
FROM python:3-alpine

# Create and change to the app directory
WORKDIR /app

# Copy local code to the container image
COPY pyproject.toml ./
COPY README.md ./
COPY backend/ ./backend/
COPY scripts/ ./scripts/

# Install project dependencies
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir .

# Run the web service on container startup
CMD ["uvicorn", "backend.api.main:app", "--host", "0.0.0.0", "--port", "8000"]